// Generated by hale (`--target wasm32`). Loads and runs the module.
// Node:    node THISFILE
// Browser: import { run } from "./THISFILE"; run(canvas?, opts?);
const WASM_FILE = "main.wasm";

export async function run(glue) {
  let mem = null;
  const u8 = () => new Uint8Array(mem.buffer);
  const dv = () => new DataView(mem.buffer);
  const cstr = (p) => {
    const m = u8(); let e = p >>> 0; while (m[e]) e++;
    return new TextDecoder().decode(m.subarray(p >>> 0, e));
  };
  // Line-buffered console output.
  let buf = "";
  const emit = (s) => {
    buf += s; let nl;
    while ((nl = buf.indexOf("\n")) >= 0) { console.log(buf.slice(0, nl)); buf = buf.slice(nl + 1); }
  };
  const flush = () => { if (buf.length) { console.log(buf); buf = ""; } };
  const align = (o, n) => (o + n - 1) & ~(n - 1);
  // Minimal printf over the wasm vararg buffer (printf(fmt, va)).
  const fmtprintf = (fmtPtr, vaPtr) => {
    const fmt = cstr(fmtPtr); const d = dv(); let off = vaPtr >>> 0; let out = "";
    for (let i = 0; i < fmt.length; i++) {
      if (fmt[i] !== "%") { out += fmt[i]; continue; }
      if (fmt[i + 1] === "%") { out += "%"; i++; continue; }
      if (fmt.startsWith("%lld", i)) { off = align(off, 8); out += d.getBigInt64(off, true).toString(); off += 8; i += 3; continue; }
      if (fmt.startsWith("%g", i))  { off = align(off, 8); out += String(d.getFloat64(off, true)); off += 8; i += 1; continue; }
      if (fmt.startsWith("%s", i))  { off = align(off, 4); const sp = d.getUint32(off, true); off += 4; out += cstr(sp); i += 1; continue; }
      out += fmt[i]; // unrecognized specifier: pass through
    }
    return out;
  };
  const writers = {
    puts:    (p) => { emit(cstr(p) + "\n"); return 0; },
    printf:  (f, va) => { emit(fmtprintf(f, va)); return 0; },
    fputs:   (p) => { emit(cstr(p)); return 0; },
    putchar: (c) => { emit(String.fromCharCode(c & 0xff)); return 0; },
    // Built-in @ffi("js") host import: console debug from Hale.
    console_log: (p) => { console.log(cstr(p)); return 0; },
    // libm: std::math lowers sin/cos/tan/... to these libm symbols, which
    // a self-contained wasm build has no library for. JS `Math` is the
    // natural host provider in the browser/node, so std::math works under
    // wasm with no app glue. (sqrt/fabs usually lower to native wasm
    // instructions and won't appear as imports; harmless to provide.)
    sin: Math.sin, cos: Math.cos, tan: Math.tan,
    asin: Math.asin, acos: Math.acos, atan: Math.atan, atan2: Math.atan2,
    sqrt: Math.sqrt, exp: Math.exp, log: Math.log, pow: Math.pow,
    tanh: Math.tanh, floor: Math.floor, ceil: Math.ceil, fabs: Math.abs,
  };
  // User-supplied @ffi("js") host imports (canvas, input, ws, ...). The
  // factory receives helpers for reading wasm memory; its functions
  // override the built-ins above. `run(glue)` is how an app wires its
  // host surface.
  if (typeof glue === "function") {
    const helpers = {
      cstr,
      mem: () => mem,
      u8, dv,
      str: cstr,
    };
    Object.assign(writers, glue(helpers));
  }

  // Load bytes (Node fs / browser fetch), relative to this module.
  let bytes;
  const isNode = typeof process !== "undefined" && process.versions && process.versions.node;
  if (isNode) {
    const { readFileSync } = await import("node:fs");
    const { fileURLToPath } = await import("node:url");
    const { dirname, join } = await import("node:path");
    bytes = readFileSync(join(dirname(fileURLToPath(import.meta.url)), WASM_FILE));
  } else {
    bytes = await (await fetch(new URL(WASM_FILE, import.meta.url))).arrayBuffer();
  }

  // Provide every host import the module declares: console writers for
  // the libc-output set, inert no-ops for the rest (gated-out IO/thread
  // teardown residue that never executes on the compute path).
  const mod = await WebAssembly.compile(bytes);
  const env = {};
  for (const im of WebAssembly.Module.imports(mod)) {
    if (im.kind !== "function") continue;
    env[im.name] = writers[im.name] || (() => 0);
  }
  const instance = await WebAssembly.instantiate(mod, { env });
  mem = instance.exports.memory;
  // Entry-inversion: if the module exports `_hale_start`, it sets up a
  // PERSISTENT program arena and the host then drives the `@export` fns
  // (e.g. per requestAnimationFrame). `main` is NOT called in that mode
  // — its create+destroy of the arena would clobber the persistent one.
  // A classic program (no `_hale_start`) runs `main` once as before.
  if (instance.exports._hale_start) instance.exports._hale_start();
  else if (instance.exports.main) instance.exports.main(0, 0);
  flush();
  return instance;
}

if (typeof process !== "undefined" && process.versions && process.versions.node) {
  run().catch((e) => { console.error(e); process.exit(1); });
}
